name: base
dependencies:
  - python=3.12 
  - pip
  - cftime
  - fsspec
  - geopandas
  - numpy
  - pandas
  - rioxarray
  - s3fs
  - xarray
  - zarr
  - dask
  - python-dotenv
  - pyresample
  - pykdtree=1.3.13=py312hc0a28a1_2
  - shapely
  - scikit-downscale
  - pip:
      - dask-cloudprovider==2024.9.1
      - fsspec==2025.2.0
      - kerchunk==0.2.7
      - netcdf4==1.7.2
      - numcodecs==0.15.1
      - pathspec==0.12.1
      - patsy==0.5.6
      - statsmodels==0.14.4
      - xarray==2025.1.1